---
title: "plant data cleanup"
output: html_document
date: "2025-09-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(lubridate)

```

# Densiometer canopy cover
```{r}

densiometer_raw = read_csv(here("data_raw/plant_data/TRACE_canopy_cover_densiometer_RAW(raw data).csv"))

```


```{r}

densiometer = densiometer_raw %>% 
  mutate(canopy.open_percent_densiometer = (n.conversion + s.conversion + e.conversion + w.conversion)/4,
         date = dmy(date),
         plot) %>% 
  select(date, plot, canopy.open_percent_densiometer)
  

```


# Canopy LAI

```{r}

lai_raw = read_csv(here("data_raw/plant_data/TRACE_canopy_LAI_summary - 2025 02 21(LAI by plot - tidy).csv")) 

```

```{r}

lai = lai_raw %>% 
  clean_names() %>% 
  mutate(date = mdy(date),
         plot = as.numeric(str_remove(plot, "P"))) %>% 
  group_by(date, plot) %>% 
  summarise(lai_m2.m2_mean = mean(lai, na.rm = T),
            lai_m2.m2_SD = sd(lai, na.rm = T)) %>% 
  rename_with(~ paste0(., "_lai.canopy"), c(-date, -plot))
  
```

# Plant Height

```{r}
plant_height_raw = read_csv(here("data_raw/plant_data/TRACE_plant_height_measurements_summary(plot summary).csv"))
```

```{r}

plant_height = plant_height_raw %>% 
  clean_names() %>% 
  mutate(date = mdy(date)) %>% 
  select(-treatment) %>% 
  rename(plantheight_cm_mean = height_avg_plot,
         plantheight_cm_max = height_max_plot,
         n.plants_count = n,
         plantheight_cm_SD = sd,
         plantheight_cm_se = se) %>% 
  rename_with(~ paste0(., "_plant.height"), c(-date, -plot))

```


# Plant Apparency

```{r}

apparency_raw = read_csv(here("data_raw/plant_data/TRACE_plant_apparency_measurements_summary(plot summary).csv"))

```

```{r}

apparency = apparency_raw %>% 
  clean_names() %>% 
  mutate(date = mdy(date)) %>% 
  select(-treatment, -n) %>% 
  rename(foliar.apparency = foliar_intercept_mean) %>%
  pivot_wider(id_cols = c(date, plot), names_from = height, values_from = c(foliar.apparency, sd, se), names_sep = ".") %>% 
  rename_with(~ paste0(., "_count"), starts_with("foliar")) %>% 
  rename_with(~ paste0(., "_count_SD"), starts_with("sd")) %>% 
  rename_with(~ paste0(., "_count_SE"), starts_with("se")) %>% 
  rename_with(~ str_replace(., "sd.", "foliar.apparency."), starts_with("sd")) %>% 
  rename_with(~ str_replace(., "se.", "foliar.apparency."), starts_with("se")) %>% 
  rename_with(~ paste0(., "_apparency"), c(-date, -plot))
  

```



# All Plant

```{r}
all_plant = lai %>% 
  full_join(densiometer, join_by(date, plot)) %>% 
  full_join(plant_height, join_by(date, plot)) %>% 
  full_join(apparency, join_by(date, plot))


# write_csv(all_plant, file = here("data_cleaned/plant_data.csv"), na = "")
```


# Litterfall

```{r}

litter_raw = read.csv(here("data_raw/plant_data/TRACE_litterfall_data_raw_20230324(litterfall_production_per_baske).csv"))

```

```{r}

litter = litter_raw %>% 
  group_by(date, method) %>% 
  summarise(littermass = mean(wt.kg.ha)) %>% 
  pivot_wider(id_cols = date, names_from = method, values_from = littermass) %>% 
  mutate(date = mdy(date)) %>% 
  rename_with(~ str_replace(., "sample.wt", "litter"), c(-date)) %>% 
  rename_with(~ paste0(., "_kg.ha_mean_litter"), c(-date))

# write_csv(litter, file = here("data_cleaned/litter.csv"), na = "")


```


# Roots
```{r}
totProd=read.csv("data_raw/ess_dive_1f9df391a77aeeb_20241028T151655779170/data/totProdfinal2Dec9.2019.16.12.20.csv")

Tubes <- read.csv("data_raw/ess_dive_1f9df391a77aeeb_20241028T151655779170/data/Tubes.csv")
#make all columns numeric
totProd[,c("session","prodbybin","mortbybin","prod.mg.cm3","mort.mg.cm3","prod.mg.cm2","mort.mg.cm2","stock.mg.cm2","stock.mg.cm3")] <- sapply(totProd[,c("session","prodbybin","mortbybin","prod.mg.cm3","mort.mg.cm3","prod.mg.cm2","mort.mg.cm2","stock.mg.cm2","stock.mg.cm3")],as.numeric)
totProd$date=as.character(totProd$date)
totProd$date=as.Date(totProd$date)


```


```{r}
totProdSAS=aggregate(data=totProd,cbind(len.mm.cm2,mortLength.mm.cm2.day,dlen.mm.cm2.day,
                                        SA.m2.m2,morSA.m2.m2.day,prodSA.m2.m2.day,
                                        stock.newRMLg.m2,prod2.newRMLg.m2.day,mort.newRMLg.m2.day)~
                       treatment+tube+hurricane+session+depthbin.cm.+date+plot,FUN=sum,na.rm=T)



totProdSAS$dlen.mm.cm2.day[totProdSAS$dlen.mm.cm2.day<0]=0
totProdSAS$mortLength.mm.cm2.day[totProdSAS$mortLength.mm.cm2.day<0]=0
totProdSAS$prodSA.m2.m2.day[totProdSAS$prodSA.m2.m2.day<0]=0
totProdSAS$morSA.m2.m2.day[totProdSAS$morSA.m2.m2.day<0]=0
#totProdSAS$prod.newRMLg.m2.day[totProdSAS$prod.newRMLg.m2.day<0]=0
totProdSAS$prod2.newRMLg.m2.day[totProdSAS$prod2.newRMLg.m2.day<0]=0
totProdSAS$mort.newRMLg.m2.day[totProdSAS$mort.newRMLg.m2.day<0]=0
#totProdSAS$prodbystock.mg.cm2.day[totProdSAS$prodbystock.mg.cm2.day<0]=0


### by plot/depth aggregate
totProdplot=aggregate(data=totProdSAS,cbind(dlen.mm.cm2.day,mortLength.mm.cm2.day,len.mm.cm2,
                                            prodSA.m2.m2.day,morSA.m2.m2.day,SA.m2.m2,
                                            stock.newRMLg.m2,prod2.newRMLg.m2.day,mort.newRMLg.m2.day)~
                        treatment+depthbin.cm.+hurricane+session+date+plot,FUN=mean,na.rm=T)
```

```{r}
mr_data = totProdplot %>% 
  select(-treatment, -hurricane, -session) %>% 
  rename_with(~ str_replace(., ".mm.cm2", "_mm.cm2"), c(-date)) %>% #root length mm/cm^2
  rename_with(~ str_replace(., ".m2.m2", "_m2.m2"), c(-date)) %>%  #root SA M^2/m^2
  rename_with(~ str_replace(., ".newRMLg.m2", "_g.m2"), c(-date)) %>% 
  rename_with(~ str_replace(., "dlen", "rootgrowthlength"), c(-date)) %>% 
  rename_with(~ str_replace(., "mort", "rootmortality"), c(-date)) %>% 
  rename_with(~ str_replace(., "len_", "rootlength_"), c(-date)) %>% 
  rename_with(~ str_replace(., "prodSA", "rootgrowthSA"), c(-date)) %>% 
  rename_with(~ str_replace(., "morSA", "rootmortalitySA"), c(-date)) %>% 
  rename_with(~ str_replace(., "morSA", "rootmortalitySA"), c(-date)) %>% 
  rename_with(~ str_replace(., "stock", "rootstock"), c(-date)) %>% 
  rename_with(~ str_replace(., "prod2", "rootgrowth"), c(-date)) %>% 
  mutate(depthbin.cm. = factor(depthbin.cm., levels = paste(seq(0,110, by = 10), seq(10,120, by = 10), sep = "-"), ordered = T)) %>% 
  group_by(plot, date) %>% 
  arrange(depthbin.cm.) %>% 
  pivot_wider(id_cols = c(date, plot), names_from = depthbin.cm., values_from = colnames(.)[5:12])
  

# write_csv(mr_data, file = here("data_cleaned/minirhizotron.csv"), na = "")

```

# Root respiration


```{r}

root_resp_raw = read_csv(here("data_raw/plant_data/rootRespiration_TRACE_MAR2017-OCT2020.csv"))

```





## Clean colnames func


```{r}
library(dplyr)
library(stringr)
library(purrr)


rename_to_var_unit_depth <- function(nms) {
  map_chr(nms, function(x) {
    original <- x
    s <- x |>
      str_to_lower() |>
      str_replace_all("[^a-z0-9_]", "_") |>
      str_replace_all("_+", "_") |>
      str_remove("^_") |>
      str_remove("_$")

    # ---- keep keys/exceptions exactly ----
    if (s %in% c("plot", "date", "length_cm")) return(original)

    # ---- depth (surf, deepcm<digits>, or 0_10 style) ----
    depth <- str_extract(s, "(?:^|_)(surf|deepcm\\d+|\\d+_\\d+)(?:_|$)")
    depth <- if (!is.na(depth)) str_remove_all(depth, "^_|_$") else NA_character_
    if (!is.na(depth)) {
      s <- s |>
        str_replace(paste0("(^|_)", depth, "(_|$)"), "\\1\\2") |>
        str_replace_all("_+", "_") |>
        str_remove("^_") |>
        str_remove("_$")
    }

    # ---- unit detection (ordered) ----
    # also detect count if the name ends in "_n"
    unit <- case_when(
      str_detect(s, "nmol.*co2.*g_1.*s_1") ~ "nmolCO2.g.s",
      str_detect(s, "mmol.*g_1.*d_1")      ~ "mmol.g.d",
      str_detect(s, "(^|_)g_c_d_1($|_)")   ~ "g.C.d",
      str_detect(s, "(^|_)ug_g_1($|_)")    ~ "ug.g",
      str_detect(s, "(^|_)cm_g_1($|_)")    ~ "cm.g",
      str_detect(s, "(^|_)g_cm_3($|_)")    ~ "g.cm-3",
      str_detect(s, "(^|_)cm3cm_3($|_)")   ~ "cm3.cm-3",
      str_detect(s, "(^|_)cm2($|_)")       ~ "cm2",
      str_detect(s, "(^|_)cm3($|_)")       ~ "cm3",
      str_detect(s, "(^|_)mm($|_)")        ~ "mm",
      str_detect(s, "(^|_)percent($|_)")   ~ "percent",
      str_detect(s, "_n$")                 ~ "count",
      TRUE ~ NA_character_
    )

    # ---- remove unit tokens from 's' (leaving just varname bits) ----
    s <- s |>
      str_replace("nmol_co2_g_1_s_1", "") |>
      str_replace("mmolg_1d_1", "") |>
      str_replace("(\\b|_)g_c_d_1(\\b|_)", "_") |>
      str_replace("(\\b|_)ug_g_1(\\b|_)", "_") |>
      str_replace("(\\b|_)cm_g_1(\\b|_)", "_") |>
      str_replace("(\\b|_)g_cm_3(\\b|_)", "_") |>
      str_replace("(\\b|_)cm3cm_3(\\b|_)", "_") |>
      str_replace("(\\b|_)cm2(\\b|_)", "_") |>
      str_replace("(\\b|_)cm3(\\b|_)", "_") |>
      str_replace("(\\b|_)mm(\\b|_)", "_") |>
      str_replace("(\\b|_)percent(\\b|_)", "_") |>
      str_replace("_n$", "") |>
      # remove trailing "..._1soil" and any residual "_soil" (but not the leading "soil_")
      str_replace("_1soil$", "") |>
      str_replace("_soil$", "") |>
      str_replace_all("_+", "_") |>
      str_remove("^_") |>
      str_remove("_$")

    # ---- source prefix (for varname), but do NOT append as unit ----
    src <- case_when(
      str_starts(s, "soil_") ~ "soil",
      str_starts(s, "root_") ~ "root",
      TRUE ~ NA_character_
    )
    rest <- if (!is.na(src)) str_remove(s, paste0("^", src, "_")) else s

    # ---- analyte token mapping ----
    toks <- if (rest == "") character(0) else str_split(rest, "_", simplify = TRUE)
    if (length(toks)) {
      analyte <- tolower(toks[1])
      analyte_std <- case_when(
        analyte == "c"   ~ "C",
        analyte == "n"   ~ "N",
        analyte == "po4" ~ "PO4",
        analyte == "nh4" ~ "NH4",
        analyte == "no3" ~ "NO3",
        TRUE ~ toks[1]
      )
      remainder <- if (length(toks) > 1) toks[-1] else character(0)
    } else {
      analyte_std <- character(0)
      remainder <- character(0)
    }

    # ---- compose varname with dots INSIDE varname only ----
    varname <- paste(
      c(na.omit(src), analyte_std, remainder),
      collapse = "."
    ) |>
      str_replace_all("\\.+", ".") |>
      str_remove("^\\.") |>
      str_remove("\\.$")

    # ---- assemble final: varname_unit_depth ----
    paste0(
      varname %||% "",
      if (!is.na(unit)) paste0("_", unit) else "",
      if (!is.na(depth)) paste0("_", depth) else ""
    )
  })
}



```



```{r}

root_resp = root_resp_raw %>% 
  clean_names() %>% 
  mutate(date_time_measured = mdy(date_time_measured),
         date_time_installed = mdy(date_time_installed))


root_ig = root_resp %>% 
  filter(ig_or_soil == "IG") %>% 
  select(-ig_or_soil, -campaign, -core, -rep, -treatment, - year_month, -plots_on_off, -pre_post_hurricane) %>% 
  rename(date = date_time_measured) %>% 
  relocate(date) %>% 
  rename_with(rename_to_var_unit_depth) %>% 
  rename_with(~ str_replace(., ".ug", "_ug"), c(-date)) %>% 
  rename_with(~ str_replace(., "mass.g", "mass_g"), c(-date)) %>% 
  rename_with(~ str_replace(., "-", ""), c(-date)) %>% 
  rename_with(~ str_replace(., "\\.c", "_c"), c(-date)) %>% 
  rename_with(~ str_replace(., ".1", ""), c(-date)) %>% 
  rename_with(~ paste0(., "_rootigcores"), c(-date, -plot))


# write_csv(root_ig, file = here("data_cleaned/rootig.csv"), na = "")

```


```{r}
root_soil = root_resp %>% 
  filter(ig_or_soil == "soil") %>% 
  select(-date_time_installed, -ig_or_soil, -campaign, - core, -rep, -treatment, -days_in_plots, - year_month, -plots_on_off, -pre_post_hurricane) %>% 
  rename(date = date_time_measured) %>% 
  relocate(date) %>% 
  rename_with(rename_to_var_unit_depth) %>% 
  rename_with(~ str_replace(., ".ug", "_ug"), c(-date)) %>% 
  rename_with(~ str_replace(., "mass.g", "mass_g"), c(-date)) %>% 
  rename_with(~ str_replace(., "-", ""), c(-date)) %>% 
  rename_with(~ str_replace(., "\\.c", "_c"), c(-date)) %>% 
  rename_with(~ str_replace(., ".1", ""), c(-date)) %>% 
  rename_with(~ paste0(., "_rootsoilcores"), c(-date, -plot))

# write_csv(root_soil, file = here("data_cleaned/rootsoil.csv"), na = "")



```

