---
title: "BGC First Look"
output: html_document
date: "2025-09-19"
---
# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(lubridate)

```

#Plots
```{r}
treatment = tibble(
  plot = c(1:6),
  treatment = rep(c("cont", "warm"), 3)
)


```

# Ingrowth cores

```{r}

ingrowth_cores = read_csv(here("data_raw/BGC_data/csv/TRACE_ingrowth_cores.csv"))
ingrowth_fill = read_csv(here("data_raw/BGC_data/csv/TRACE_ingrowth_cores_fill.csv"))

```


```{r}
fill = ingrowth_fill %>% 
  clean_names() %>% 
  mutate(across(3:16, as.numeric)) %>% 
  mutate(date = mdy(date),
         start = ymd(case_when(date == "2017-11-02" ~ "2017-11-01",
                           date == "2017-03-01" ~ "2017-03-01",
                           date == "2018-07-25" ~ "2017-07-01",
                           date == "2018-09-26" ~ "2018-09-01",
                           date == "2019-03-20" ~ "2019-03-01",
                           date == "2019-11-25" ~ "2019-11-01")),
         end = ymd(case_when(date == "2017-11-02" ~ "2017-11-30",
                           date == "2017-03-01" ~ "2017-03-31",
                           date == "2018-07-25" ~ "2017-07-31",
                           date == "2018-09-26" ~ "2018-09-30",
                           date == "2019-03-20" ~ "2019-03-31",
                           date == "2019-11-25" ~ "2019-11-30"))) %>% 
  group_by(date, start, end) %>% 
  summarise(tc = mean(tc, na.rm = T),
            tn = mean(tn, na.rm = T),
            tc_tn = mean(tc_tn, na.rm = T),
            nh4 = mean(nh4, na.rm = T),
            no3 = mean(no3, na.rm = T),
            nh4_min_rate = mean(nh4_min_rate, na.rm = T),
            no3_min_rate = mean(no3_min_rate, na.rm = T),
            po4 = mean(po4, na.rm = T),
            ext_c = mean(ext_c, , na.rm = T),
            ext_n = mean(ext_n, na.rm = T),
            ubial_c = mean(ubial_c, na.rm = T),
            ubial_n = mean(ubial_n, na.rm = T),
            ubial_p = mean(ubial_p, na.rm = T),
            ubial_c_n = mean(ubial_c_n, na.rm = T)) %>% 
    filter(!is.na(start)) %>% 
  mutate(type = "init")

ingrowth_rm= ingrowth_cores %>% 
  clean_names() %>% 
  mutate(across(6:19, as.numeric)) %>% 
  mutate(date_installed = mdy(date_installed),
         date_removed = mdy(date_removed)) %>% 
  mutate(type = "rm")


ingrowth = ingrowth_cores %>% 
  clean_names() %>% 
  mutate(across(6:19, as.numeric)) %>% 
  mutate(date_installed = mdy(date_installed),
         date_removed = mdy(date_removed)) %>% 
  filter(!is.na(date_installed)) %>% 
  left_join(fill, by = join_by(between(date_installed, start, end)), suffix = c(".rm", ".init")) %>% 
  mutate(
    tc.change = tc.rm - tc.init,
    tn.change = tn.rm - tc.init,
    tc_tn.change = tc_tn.rm - tc_tn.init,
    nh4.change = nh4.rm - nh4.init,
    no3.change = no3.rm - no3.init,
    nh4_min_rate.change = nh4_min_rate.rm - nh4_min_rate.init,
    no3_min_rate.change = no3_min_rate.rm - no3_min_rate.init,
    po4.change = po4.rm - po4.init, 
    ext_c.change = ext_c.rm - ext_c.init,
    ext_n.change = ext_n.rm - ext_n.init,
    ubial_c.change = ubial_c.rm - ubial_c.init,
    ubial_n.change = ubial_n.rm - ubial_n.init,
    ubial_p.change = ubial_p.rm - ubial_p.init,
    ubial_c_n.change = ubial_c_n.rm - ubial_c_n.init
  ) %>% 
  left_join(treatment, by = "plot")

inits = ingrowth %>% 
  select(core, plot, rep, date_installed, date_removed, ends_with(".init")) %>% 
  rename_with(~ gsub(".init", "", .x), ends_with(".init")) %>% 
  mutate(type = "init",
         date = date_installed)

rms = ingrowth %>% 
  select(core, plot, rep, date_installed, date_removed, ends_with(".rm")) %>% 
  rename_with(~ gsub(".rm", "", .x), ends_with(".rm")) %>% 
  mutate(type = "rm",
         date = date_removed)



```

```{r}
ingrowth_tidy = ingrowth %>% 
  group_by(plot, date_removed, date_installed) %>% 
  summarise(tc_percent_mean_traceingrowthcores = mean(tc.rm, na.rm = T),
            tc_percent_SD_traceingrowthcores = sd(tc.rm, na.rm = T),
            tn_percent_mean_traceingrowthcores = mean(tn.rm, na.rm = T),
            tn_percent_SD_traceingrowthcores = sd(tn.rm, na.rm = T),
            tc.tn_ratio_mean_traceingrowthcores = mean(tc_tn.rm, na.rm = T),
            tc.tn_ratio_SD_traceingrowthcores = sd(tc_tn.rm, na.rm = T),
            nh4_ugN.gsoil_mean_traceingrowthcores = mean(nh4.rm, na.rm = T),
            nh4_ugN.gsoil_SD_traceingrowthcores = sd(nh4.rm, na.rm = T),
            no3_ugN.gsoil_mean_traceingrowthcores = mean(no3.rm, na.rm = T),
            no3_ugN.gsoil_SD_traceingrowthcores = sd(no3.rm, na.rm = T),
            nh4minrate_ugN.gsoil.day_mean_traceingrowthcores = mean(nh4_min_rate.rm, na.rm = T),
            nh4minrate_ugN.gsoil.day_SD_traceingrowthcores = sd(nh4_min_rate.rm, na.rm = T),
            no3_min_rate_ugN.gsoil.day_mean_traceingrowthcores = mean(no3_min_rate.rm, na.rm = T),
            no3_min_rate_ugN.gsoil.day_SD_traceingrowthcores = sd(no3_min_rate.rm, na.rm = T),
            po4_ugP.gsoil_mean_traceingrowthcores = mean(po4.rm, na.rm = T),
            po4_ugP.gsoil_SD_traceingrowthcores = sd(po4.rm, na.rm = T),
            ext.c_ug.gsoil_mean_traceingrowthcores = mean(ext_c.rm, na.rm = T),
            ext.c_ug.gsoil_SD_traceingrowthcores = sd(ext_c.rm, na.rm = T),
            ext.n_ug.gsoil_mean_traceingrowthcores = mean(ext_n.rm, na.rm = T),
            ext.n_ug.gsoil_SD_traceingrowthcores = sd(ext_n.rm, na.rm = T),
            ubial.c_ug.gsoil_mean_traceingrowthcores = mean(ubial_c.rm, na.rm = T),
            ubial.c_ug.gsoil_SD_traceingrowthcores = sd(ubial_c.rm, na.rm = T),
            ubial.n_ug.gsoil_mean_traceingrowthcores = mean(ubial_n.rm, na.rm = T),
            ubial.n_ug.gsoil_SD_traceingrowthcores = sd(ubial_n.rm, na.rm = T),
            ubial.p_ug.gsoil_mean_traceingrowthcores = mean(ubial_p.rm, na.rm = T),
            ubial.p_ug.gsoil_SD_traceingrowthcores = sd(ubial_p.rm, na.rm = T),
            ubial.c.n_ratio_mean_traceingrowthcores = mean(ubial_c_n.rm, na.rm = T),
            ubial.c.n_ratio_SD_traceingrowthcores = sd(ubial_c_n.rm, na.rm = T),
            tc.change_percent_mean_traceingrowthcores = mean(tc.change, na.rm = T),
            tc.change_percent_SD_traceingrowthcores = sd(tc.change, na.rm = T),
            tn.change_percent_mean_traceingrowthcores = mean(tn.change, na.rm = T),
            tn.change_percent_SD_traceingrowthcores = sd(tn.change, na.rm = T),
            tc.tn.change_ratio_mean_traceingrowthcores = mean(tc_tn.change, na.rm = T),
            tc.tn.change_ratio_SD_traceingrowthcores = sd(tc_tn.change, na.rm = T),
            nh4.change_ugN.gsoil_mean_traceingrowthcores = mean(nh4.change, na.rm = T),
            nh4.change_ugN.gsoil_SD_traceingrowthcores = sd(nh4.change, na.rm = T),
            no3.change_ugN.gsoil_mean_traceingrowthcores = mean(no3.change, na.rm = T),
            no3.change_ugN.gsoil_SD_traceingrowthcores = sd(no3.change, na.rm = T),
            nh4_min_rate.change_ugN.gsoil.day_mean_traceingrowthcores = mean(nh4_min_rate.change, na.rm = T),
            nh4_min_rate.change_ugN.gsoil.day_SD_traceingrowthcores = sd(nh4_min_rate.change, na.rm = T),
            no3_min_rate.change_ugN.gsoil.day_mean_traceingrowthcores = mean(no3_min_rate.change, na.rm = T),
            no3_min_rate.change_ugN.gsoil.day_SD_traceingrowthcores = sd(no3_min_rate.change, na.rm = T),
            po4.change_ugP.gsoil_mean_traceingrowthcores = mean(po4.change, na.rm = T),
            po4.change_ugP.gsoil_SD_traceingrowthcores = sd(po4.change, na.rm = T),
            ext.c.change_ug.gsoil_mean_traceingrowthcores = mean(ext_c.change, na.rm = T),
            ext.c.change_ug.gsoil_SD_traceingrowthcores = sd(ext_c.change, na.rm = T),
            ext.n.change_ug.gsoil_mean_traceingrowthcores = mean(ext_n.change, na.rm = T),
            ext.n.change_ug.gsoil_SD_traceingrowthcores = sd(ext_n.change, na.rm = T),
            ubial.c.change_ug.gsoil_mean_traceingrowthcores = mean(ubial_c.change, na.rm = T),
            ubial.c.change_ug.gsoil_SD_traceingrowthcores = sd(ubial_c.change, na.rm = T),
            ubial.n.change_ug.gsoil_mean_traceingrowthcores = mean(ubial_n.change, na.rm = T),
            ubial.n.change_ug.gsoil_SD_traceingrowthcores = sd(ubial_n.change, na.rm = T),
            ubial.p.change_ug.gsoil_mean_traceingrowthcores = mean(ubial_p.change, na.rm = T),
            ubial.p.change_ug.gsoil_SD_traceingrowthcores = sd(ubial_p.change, na.rm = T),
            ubial.c.n.change_ug.gsoil_mean_traceingrowthcores = mean(ubial_c_n.change, na.rm = T),
            ubial.c.n.change_ug.gsoil_SD_traceingrowthcores = sd(ubial_c_n.change, na.rm = T)) %>% 
  rename(date = date_removed,
         date_installed_traceingrowthcores = date_installed)


# write_csv(ingrowth_tidy, file = here("data_cleaned/ingrowth_cores.csv"), na = "")

```



```{r}



ggplot(ingrowth) + 
  geom_segment(aes(x = date_installed, xend = date_removed,
                   y = ubial_c.init, yend = ubial_c.rm, color = as.factor(date))) +
  facet_wrap(plot~., nrow = 3) +
  scale_x_date(date_breaks = "3 month", date_labels = "%b-%Y") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 


```




# Porewater Chemistry

```{r}
pwc_data = read_csv(here("data_raw/BGC_data/csv/TRACE_porewater_chemistry.csv"), skip = 1)
```

```{r}
pwc = pwc_data %>% 
  clean_names() %>% 
  separate_wider_delim(sample_id, delim = "-", names = c("plot", "depth"), too_few = "align_start") %>% 
  mutate(date = mdy(sample_name)) %>% 
  filter(!is.na(plot),
         !is.na(depth)) %>% 
  rename(volume = x4) %>% 
  select(date, where(~!all(is.na(.))),
         -x1, -sample_name, -notes, -npoc, -tn) %>% 
  mutate(volume = as.numeric(volume),
         mg_npoc = as.numeric(mg_npoc),
         mg_tdn = as.numeric(mg_tdn),
         plot = as.numeric(plot),
         depth = as.factor(depth)) %>% 
  rename(date = date,
         plot = plot,
         volume_ml = volume,
         npoc_mg.l = mg_npoc_l,
         npoc_mg = mg_npoc,
         tdn_mg.l = mg_tdn_l,
         tdn_mg = mg_tdn) %>% 
  pivot_wider(id_cols = c(date, plot), names_from = depth, values_from = c(volume_ml, npoc_mg.l, npoc_mg, tdn_mg.l, tdn_mg), values_fill = NA) %>% 
  rename_with(~ paste0(., "cm_pwchemistry"), c(-date, -plot))

# write_csv(pwc, file = here("data_cleaned/pwchemistry.csv"), na = "")
  
# ASK Gabriel what the columns mean

```

```{r}
ggplot(pwc, aes(x = date, y = tdn_mg.l_pwchemistry)) +
  geom_point() + 
  facet_wrap(plot~depth_pwchemistry, nrow = 6, ncol = 3) +
  scale_x_date(date_breaks = "3 month", date_labels = "%b-%Y") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
```

# Lysimiter

```{r}

lys_chem_toctn_raw_head = read_csv(here("data_raw/BGC_data/csv/TRACE_surface_lysimiter_chemistry_toctdn_working.csv"), col_names = F, n_max = 1)
lys_chem_toctn_raw_data = read_csv(here("data_raw/BGC_data/csv/TRACE_surface_lysimiter_chemistry_toctdn_working.csv"), skip = 2, col_names = F)
colnames(lys_chem_toctn_raw_data) = unlist(lys_chem_toctn_raw_head)

lys_chem_westco_raw = read_csv(here("data_raw/BGC_data/csv/TRACE_surface_lysimiter_chemistry_westco.csv"))
```

```{r}
lys_chem_cn = lys_chem_toctn_raw_data %>% 
  clean_names() %>% 
  mutate(date = dmy(date),
         across(3:9, as.numeric)) %>% 
  select(-npoc, -tn, -na) %>% 
  rename(npoc_ug.mL = npoc_dilution,
         tn_ug.mL = tn_dilution)

lys_chem_westco = lys_chem_westco_raw %>% 
  clean_names() %>% 
  mutate(date = mdy(date)) %>% 
  select(-run, -date_and_plot) %>% 
  mutate(across(3:9, ~case_when(. == "BDL" ~ "0",
                                .default = .))) %>%
  mutate(across(2:9, as.numeric)) %>% 
  rename(po4_ugP.mL = po4_p_mg_l,
         po4_ugP = po4_p_ug,
         no3_ugN.mL = no3_n_mg_l,
         no3_ugN = no3_n_ug,
         nh4_ugN.mL = nh4_n_mg_l,
         nh4_ugN = nh4_n_ug)


lys_chem = lys_chem_cn %>% 
  left_join(lys_chem_westco, by = join_by(plot, date)) %>% 
  rename_with(~ paste0(., "_lysimiter.surface.chemistry"), c(-date, -plot))


# write_csv(lys_chem, file = here("data_cleaned/lysimiter.surface.chemistry.csv"), na = "")



```

```{r}
ggplot(lys_chem, aes(x = date, y = no3_ugN.mL_lysimiter.surface.chemistry)) + 
  geom_point() + 
  facet_wrap(plot~., nrow = 3, ncol = 2) +
  scale_x_date(date_breaks = "3 month", date_labels = "%b-%Y") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

# Resin

```{r}
resin_data = read_csv(here("data_raw/BGC_data/csv/TRACE_resin.csv"))
```

```{r}

resin = resin_data %>% 
  clean_names() %>% 
  mutate(installed = dmy(installed),
         removed = dmy(removed),
         across(7:8, as.numeric)) %>% 
  select(date = removed, plot, installed, 7:8) %>% 
  rename(nh4_ugN.day = ug_nh4_n_day,
         no3_ugN.day = ug_no3_n_day) %>% 
  rename_with(~ paste0(., "_resin"), c(-date, -plot))
  

write_csv(resin, file = here("data_cleaned/resin.csv"), na = "")


```


# Throughfall


```{r}
throughfall_raw = read_csv(here("data_raw/BGC_data/csv/Trace_throughfall_bgc.csv"))
```


```{r}
tf_key = tibble(collector_number = c(1:10), plot = c(NA, 1, 2, 4, NA, NA, 6, 6, 5, 3))

throughfall_plot = throughfall_raw %>% 
  clean_names() %>% 
  mutate(date = dmy(date)) %>% 
  left_join(tf_key, join_by(collector_number)) %>% 
  mutate(volume_m_l = str_remove(volume_m_l, ",")) %>% 
  mutate(across(3:7, as.numeric)) %>% 
  group_by(date, plot) %>% 
  summarise(tfvol_ml_plotmean = mean(volume_m_l, na.rm = T),
            npoc_mgC.L_plotmean = mean(npoc_measured_mg_c_l, na.rm = T),
            npoc_mgC_plotmean = mean(npoc_final_mg, na.rm = T),
            tdn_mgN.L_plotmean = mean(tdn_measured_mg_n_l, na.rm = T),
            tdn_mgN_plotmean = mean(tdn_final_mg, na.rm = T)) %>% 
  filter(!is.na(plot))


throughfall_date = throughfall_raw %>% 
  clean_names() %>% 
  mutate(date = dmy(date)) %>% 
  mutate(volume_m_l = str_remove(volume_m_l, ",")) %>% 
  mutate(across(3:7, as.numeric)) %>% 
  group_by(date) %>% 
  summarise(tfvol_ml_sitemean = mean(volume_m_l, na.rm = T),
            tfvol_ml_siteSD = sd(volume_m_l, na.rm = T),
            npoc_mgC.L_sitemean = mean(npoc_measured_mg_c_l, na.rm = T),
            npoc_mgC.L_siteSD= sd(npoc_measured_mg_c_l, na.rm = T),
            npoc_mgC_sitemean = mean(npoc_final_mg, na.rm = T),
            npoc_mgC_siteSD = sd(npoc_final_mg, na.rm = T),
            tdn_mgN.L_sitemean = mean(tdn_measured_mg_n_l, na.rm = T),
            tdn_mgN.L_siteSD = sd(tdn_measured_mg_n_l, na.rm = T),
            tdn_mgN_sitemean = mean(tdn_final_mg, na.rm = T),
            tdn_mgN_siteSD = sd(tdn_final_mg, na.rm = T))


throughfall = throughfall_plot %>% 
  left_join(throughfall_date, join_by(date)) %>% 
  rename_with(~ paste0(., "_throughfall"), c(-date, -plot))

# write_csv(throughfall, file = here("data_cleaned/throughfall.csv"), na = "")


```



# Nutrient Cores

```{r}
nutrient_raw = read_csv(here("data_raw/BGC_data/csv/Trace_nutrient_cores.csv"))
```

```{r}
nutrient = nutrient_raw %>% 
  clean_names() %>% 
  select(-starts_with("x")) %>% 
  filter_all(any_vars(!is.na(.))) %>% 
  mutate(date = mdy(date)) %>% 
  rename(tc_g.g.soil = tc,
         tn_g.g.soil = tn,
         tc.tn_ratio = tc_tn,
         nh4_ug.g.soil = nh4,
         no3_ug.g.soil = no3,
         nh4.min_ug.g.soil.day = nh4_min,
         no3.min_ug.g.soil.day = no3_min,
         po4_ug.g.soil = po4,
         ext.c_ug.g.soil = ext_c,
         ext.n_ug.g.soil = ext_n,
         ubial.c_ug.g.soil = ubial_c,
         ubial.n_ug.g.soil = ubial_n,
         ubial.p_ug.g.soil = ubial_p,
         ubial.c.n_ratio = ubial_c_n) %>% 
  group_by(date, plot) %>% 
  summarise(across(tc_g.g.soil:ubial.c.n_ratio, list(mean = ~ mean(.x, na.rm = T), SD = sd))) %>% 
  rename_with(~ paste0(., "_nutrient.cores"), c(-date, -plot))

# write_csv(nutrient, file = here("data_cleaned/nutrient.cores.csv"), na = "")


```



